export const ON_INIT = 'ON_INIT'
export const SET_AUTH = 'SET_AUTH'
export const LOADING = 'LOADING'
export const LOGOUT = 'LOGOUT'

export const GET_REQUEST = 'GET_REQUEST'
export const GET_USER_REQUEST = 'GET_USER_REQUEST'

export const SET_MODAL = 'SET_MODAL'

export const UPDATE_CONVERSATIONS = 'UPDATE_CONVERSATIONS'
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'
export const ADD_MESSAGE = 'ADD_MESSAGE'

export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION'

export const SET_MESSAGE_ALERT = 'SET_MESSAGE_ALERT'
